use super::task::SiemTask;
use super::alert::{SolidRule};
use super::common::UserRole;

pub struct SiemUseCase {
    pub name : &'static str,
    pub description : &'static str,
    pub case_logic : &'static str,
    pub limitations : &'static str,
    /// Requirements: Product, Service, Category => AND conditioned
    pub requirements : (Option<&'static str>,Option<&'static str>,Option<&'static str>),
    pub rule : Box<dyn SolidRule>,
    pub actions : Vec<SiemPlaybookStep>,
}

pub enum SiemPlaybookStep {
    /// Manual action: Name and description
    Manual(&'static str,&'static str),
    Automated(SiemAutomatedStep)
}


pub struct SiemAutomatedStep {
    /// Minimum role to execute this Step
    pub min_role : UserRole,
    /// Action to be executed, The String param is the `aggr_key` of the alert generated by the rule
    pub action : Box<dyn Fn(String) -> SiemTask>,
    /// Name of the step
    pub name  : &'static str,
    /// Description of the step
    pub description : &'static str
}